# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 530)
        MainWindow.setMinimumSize(QtCore.QSize(900, 530))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_main.setFont(font)
        self.frame_main.setStyleSheet("background: #19191A;")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_top.setFont(font)
        self.frame_top.setStyleSheet("background: #2D2D2E;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_top_main = QtWidgets.QFrame(self.frame_top)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_top_main.setFont(font)
        self.frame_top_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_main.setObjectName("frame_top_main")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_main)
        self.horizontalLayout_4.setContentsMargins(25, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_top_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #BCBCBC;")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame_top_main)
        self.frame_top_buttons = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_buttons.sizePolicy().hasHeightForWidth())
        self.frame_top_buttons.setSizePolicy(sizePolicy)
        self.frame_top_buttons.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_top_buttons.setFont(font)
        self.frame_top_buttons.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_top_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_buttons.setObjectName("frame_top_buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top_buttons)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_top_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(32, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_minimize.setFont(font)
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    background-color: transparent;\n"
"    border: 2px solid transparent;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #29292B;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1B1A1F;\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/topButtons/Resources/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setIconSize(QtCore.QSize(16, 16))
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_top_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(32, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    background-color: transparent;\n"
"    border: 2px solid transparent;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #29292B;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1B1A1F;\n"
"}")
        self.btn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/topButtons/Resources/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setIconSize(QtCore.QSize(16, 16))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.frame_top_buttons)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_center.setFont(font)
        self.frame_center.setStyleSheet("")
        self.frame_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_center)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.page_login.setFont(font)
        self.page_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_login.setAutoFillBackground(False)
        self.page_login.setObjectName("page_login")
        self.gridLayout = QtWidgets.QGridLayout(self.page_login)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_login = QtWidgets.QFrame(self.page_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_login.sizePolicy().hasHeightForWidth())
        self.frame_login.setSizePolicy(sizePolicy)
        self.frame_login.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_login.setStyleSheet("border: 2px solid #525252;\n"
"border-radius: 20px;")
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_login_enter = QtWidgets.QPushButton(self.frame_login)
        self.btn_login_enter.setMinimumSize(QtCore.QSize(90, 25))
        self.btn_login_enter.setMaximumSize(QtCore.QSize(90, 25))
        self.btn_login_enter.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_login_enter.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login_enter.setFont(font)
        self.btn_login_enter.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2E;\n"
"    color: #BCBCBC;\n"
"    border: 2px solid #525252;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #525252;\n"
"    border: 2px solid #777777;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: #2D2D2E;\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        self.btn_login_enter.setObjectName("btn_login_enter")
        self.gridLayout_2.addWidget(self.btn_login_enter, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.edit_login_pass = QtWidgets.QLineEdit(self.frame_login)
        self.edit_login_pass.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.edit_login_pass.setFont(font)
        self.edit_login_pass.setStyleSheet("QLineEdit {\n"
"    background-color: #2D2D2E;\n"
"    border-radius: 15px;\n"
"    border: 2px solid #525252;\n"
"    padding-left: 10px;\n"
"    color: #BCBCBC;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #777777;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        self.edit_login_pass.setText("")
        self.edit_login_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_login_pass.setObjectName("edit_login_pass")
        self.gridLayout_2.addWidget(self.edit_login_pass, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_login, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_login)
        self.page_home = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.page_home.setFont(font)
        self.page_home.setObjectName("page_home")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_home)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_home_add = QtWidgets.QFrame(self.page_home)
        self.frame_home_add.setStyleSheet("QFrame#frame_home_add{\n"
"border: 2px solid #525252;\n"
"border-radius: 40px;\n"
"}")
        self.frame_home_add.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_add.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_add.setObjectName("frame_home_add")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_home_add)
        self.verticalLayout_3.setContentsMargins(10, 30, 10, 30)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.edit_home_app = QtWidgets.QLineEdit(self.frame_home_add)
        self.edit_home_app.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.edit_home_app.setFont(font)
        self.edit_home_app.setStyleSheet("QLineEdit {\n"
"    background-color: #2D2D2E;\n"
"    border-radius: 15px;\n"
"    border: 2px solid #525252;\n"
"    padding-left: 10px;\n"
"    color: #BCBCBC;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #777777;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        self.edit_home_app.setText("")
        self.edit_home_app.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edit_home_app.setObjectName("edit_home_app")
        self.verticalLayout_3.addWidget(self.edit_home_app)
        self.edit_home_login = QtWidgets.QLineEdit(self.frame_home_add)
        self.edit_home_login.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.edit_home_login.setFont(font)
        self.edit_home_login.setStyleSheet("QLineEdit {\n"
"    background-color: #2D2D2E;\n"
"    border-radius: 15px;\n"
"    border: 2px solid #525252;\n"
"    padding-left: 10px;\n"
"    color: #BCBCBC;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #777777;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        self.edit_home_login.setText("")
        self.edit_home_login.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edit_home_login.setObjectName("edit_home_login")
        self.verticalLayout_3.addWidget(self.edit_home_login)
        self.edit_home_mail = QtWidgets.QLineEdit(self.frame_home_add)
        self.edit_home_mail.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.edit_home_mail.setFont(font)
        self.edit_home_mail.setStyleSheet("QLineEdit {\n"
"    background-color: #2D2D2E;\n"
"    border-radius: 15px;\n"
"    border: 2px solid #525252;\n"
"    padding-left: 10px;\n"
"    color: #BCBCBC;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #777777;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        self.edit_home_mail.setText("")
        self.edit_home_mail.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edit_home_mail.setObjectName("edit_home_mail")
        self.verticalLayout_3.addWidget(self.edit_home_mail)
        self.edit_home_pass = QtWidgets.QLineEdit(self.frame_home_add)
        self.edit_home_pass.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.edit_home_pass.setFont(font)
        self.edit_home_pass.setStyleSheet("QLineEdit {\n"
"    background-color: #2D2D2E;\n"
"    border-radius: 15px;\n"
"    border: 2px solid #525252;\n"
"    padding-left: 10px;\n"
"    color: #BCBCBC;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #777777;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        self.edit_home_pass.setText("")
        self.edit_home_pass.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edit_home_pass.setObjectName("edit_home_pass")
        self.verticalLayout_3.addWidget(self.edit_home_pass)
        self.edit_home_comment = QtWidgets.QPlainTextEdit(self.frame_home_add)
        self.edit_home_comment.setStyleSheet("QPlainTextEdit {\n"
"    background-color: #2D2D2E;\n"
"    border-radius: 15px;\n"
"    border: 2px solid #525252;\n"
"    padding-left: 10px;\n"
"    color: #BCBCBC;\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid #777777;\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        self.edit_home_comment.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.edit_home_comment.setPlainText("")
        self.edit_home_comment.setObjectName("edit_home_comment")
        self.verticalLayout_3.addWidget(self.edit_home_comment)
        self.frame_home_add_btn = QtWidgets.QFrame(self.frame_home_add)
        self.frame_home_add_btn.setObjectName("frame_home_add_btn")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_home_add_btn)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_home_add = QtWidgets.QPushButton(self.frame_home_add_btn)
        self.btn_home_add.setMinimumSize(QtCore.QSize(90, 25))
        self.btn_home_add.setMaximumSize(QtCore.QSize(90, 25))
        self.btn_home_add.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_home_add.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_home_add.setFont(font)
        self.btn_home_add.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2E;\n"
"    color: #BCBCBC;\n"
"    border: 2px solid #525252;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #525252;\n"
"    border: 2px solid #777777;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: #2D2D2E;\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/topButtons/Resources/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home_add.setIcon(icon2)
        self.btn_home_add.setObjectName("btn_home_add")
        self.horizontalLayout_8.addWidget(self.btn_home_add)
        self.btn_bot_settings_2 = QtWidgets.QPushButton(self.frame_home_add_btn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bot_settings_2.sizePolicy().hasHeightForWidth())
        self.btn_bot_settings_2.setSizePolicy(sizePolicy)
        self.btn_bot_settings_2.setMinimumSize(QtCore.QSize(90, 25))
        self.btn_bot_settings_2.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bot_settings_2.setFont(font)
        self.btn_bot_settings_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2E;\n"
"    color: #BCBCBC;\n"
"    border: 2px solid #525252;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #525252;\n"
"    border: 2px solid #777777;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: #2D2D2E;\n"
"    border: 2px solid #8D8D8D;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/topButtons/Resources/icons/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_bot_settings_2.setIcon(icon3)
        self.btn_bot_settings_2.setIconSize(QtCore.QSize(20, 20))
        self.btn_bot_settings_2.setObjectName("btn_bot_settings_2")
        self.horizontalLayout_8.addWidget(self.btn_bot_settings_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.frame_home_add_btn)
        self.horizontalLayout_7.addWidget(self.frame_home_add)
        self.list_app = QtWidgets.QListWidget(self.page_home)
        self.list_app.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_app.setStyleSheet("QListWidget{\n"
"    border: 2px solid #525252;\n"
"    color: #BCBCBC;\n"
"}")
        self.list_app.setObjectName("list_app")
        self.horizontalLayout_7.addWidget(self.list_app)
        self.stackedWidget.addWidget(self.page_home)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.stackedWidget.addWidget(self.page_settings)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_center)
        self.frame_bot = QtWidgets.QFrame(self.frame_main)
        self.frame_bot.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_bot.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_bot.setFont(font)
        self.frame_bot.setStyleSheet("background: #2D2D2E;")
        self.frame_bot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bot.setObjectName("frame_bot")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_bot)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_bot_main = QtWidgets.QFrame(self.frame_bot)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_bot_main.setFont(font)
        self.frame_bot_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bot_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bot_main.setObjectName("frame_bot_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_bot_main)
        self.horizontalLayout.setContentsMargins(25, 0, 15, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_bot_error = QtWidgets.QLabel(self.frame_bot_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_bot_error.setFont(font)
        self.label_bot_error.setStyleSheet("color: #BCBCBC;")
        self.label_bot_error.setText("")
        self.label_bot_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_bot_error.setObjectName("label_bot_error")
        self.horizontalLayout.addWidget(self.label_bot_error)
        self.label_bot_name = QtWidgets.QLabel(self.frame_bot_main)
        self.label_bot_name.setMinimumSize(QtCore.QSize(0, 0))
        self.label_bot_name.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_bot_name.setFont(font)
        self.label_bot_name.setStyleSheet("color: #BCBCBC;")
        self.label_bot_name.setText("")
        self.label_bot_name.setScaledContents(False)
        self.label_bot_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bot_name.setObjectName("label_bot_name")
        self.horizontalLayout.addWidget(self.label_bot_name)
        self.horizontalLayout_5.addWidget(self.frame_bot_main)
        self.frame_bot_buttons = QtWidgets.QFrame(self.frame_bot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_bot_buttons.sizePolicy().hasHeightForWidth())
        self.frame_bot_buttons.setSizePolicy(sizePolicy)
        self.frame_bot_buttons.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_bot_buttons.setFont(font)
        self.frame_bot_buttons.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_bot_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bot_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bot_buttons.setObjectName("frame_bot_buttons")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_bot_buttons)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_bot_logout = QtWidgets.QPushButton(self.frame_bot_buttons)
        self.btn_bot_logout.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bot_logout.sizePolicy().hasHeightForWidth())
        self.btn_bot_logout.setSizePolicy(sizePolicy)
        self.btn_bot_logout.setMinimumSize(QtCore.QSize(32, 0))
        self.btn_bot_logout.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_bot_logout.setFont(font)
        self.btn_bot_logout.setStyleSheet("QPushButton {    \n"
"    background-color: transparent;\n"
"    border: 2px solid transparent;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #29292B;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1B1A1F;\n"
"}")
        self.btn_bot_logout.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/topButtons/Resources/icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_bot_logout.setIcon(icon4)
        self.btn_bot_logout.setIconSize(QtCore.QSize(16, 16))
        self.btn_bot_logout.setObjectName("btn_bot_logout")
        self.horizontalLayout_6.addWidget(self.btn_bot_logout)
        self.btn_bot_settings = QtWidgets.QPushButton(self.frame_bot_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bot_settings.sizePolicy().hasHeightForWidth())
        self.btn_bot_settings.setSizePolicy(sizePolicy)
        self.btn_bot_settings.setMinimumSize(QtCore.QSize(32, 0))
        self.btn_bot_settings.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_bot_settings.setFont(font)
        self.btn_bot_settings.setStyleSheet("QPushButton {    \n"
"    background-color: transparent;\n"
"    border: 2px solid transparent;\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #29292B;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1B1A1F;\n"
"}")
        self.btn_bot_settings.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/topButtons/Resources/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_bot_settings.setIcon(icon5)
        self.btn_bot_settings.setIconSize(QtCore.QSize(20, 20))
        self.btn_bot_settings.setObjectName("btn_bot_settings")
        self.horizontalLayout_6.addWidget(self.btn_bot_settings)
        self.horizontalLayout_5.addWidget(self.frame_bot_buttons)
        self.verticalLayout.addWidget(self.frame_bot)
        self.verticalLayout_5.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_close, self.btn_minimize)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Copy Pass\'te"))
        self.label.setText(_translate("MainWindow", "Copy Pass\'te"))
        self.btn_login_enter.setText(_translate("MainWindow", "Вход"))
        self.edit_login_pass.setPlaceholderText(_translate("MainWindow", "Введите ключ доступа"))
        self.edit_home_app.setPlaceholderText(_translate("MainWindow", "Введите название"))
        self.edit_home_login.setPlaceholderText(_translate("MainWindow", "Введите логин"))
        self.edit_home_mail.setPlaceholderText(_translate("MainWindow", "*Опционально: Введите почту"))
        self.edit_home_pass.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.edit_home_comment.setPlaceholderText(_translate("MainWindow", "Комментарии"))
        self.btn_home_add.setText(_translate("MainWindow", "Добавить"))
        self.btn_bot_settings_2.setText(_translate("MainWindow", "Генератор"))
import files_rc
